FROM registry.access.redhat.com/ubi9/ubi-minimal

LABEL maintainer="Nishant contact@nishko.co"
ENV TZ=Asia/Kolkata
SHELL ["/bin/bash", "-lc"]

RUN microdnf update -y \
 && microdnf install -y \
    git \
    sudo \
    shadow-utils \
    tar \
 && microdnf clean all

RUN set -eux; \
    NVIM_URL="https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz"; \
    curl -fsSL -o /tmp/nvim-linux64.tar.gz "$NVIM_URL"; \
    tar -xzf /tmp/nvim-linux64.tar.gz -C /tmp; \
    mv /tmp/nvim-linux64/bin/nvim /usr/local/bin/nvim; \
    chmod +x /usr/local/bin/nvim; \
    rm -rf /tmp/nvim-linux64* /tmp/nvim-linux64.tar.gz || true

ARG USERNAME=nishko
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd --gid ${USER_GID} ${USERNAME} \
 && useradd -m --uid ${USER_UID} --gid ${USER_GID} -s /bin/bash ${USERNAME} \
 && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
 && chmod 0440 /etc/sudoers.d/${USERNAME}

WORKDIR /workspace
USER ${USERNAME}
ENV HOME=/home/${USERNAME}

CMD ["bash"]
